apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tanzu-docker-empty-1
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-docker-empty-1
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-java-web-app
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: tanzu-docker-empty-1
    spec:
      containers:
      - image: manimaranm1.azurecr.io/jul14/resiliency-build-cluster-basic/tanzu-docker-empty-1-my-apps@sha256:8454f5ce4969867f0f1dd0b810032b3462cd05eb67a140ab68c3cf3a8921a2ed
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

