apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tanzu-docker-3
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-docker-3
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-java-web-app
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: tanzu-docker-3
    spec:
      containers:
      - image: manimaranm1.azurecr.io/jul14/resiliency-build-cluster-basic/tanzu-docker-3-my-apps@sha256:164dbc7688b4ba94b1f9d1ee181ce9a5d53d3bdf81a6319ed339202f50a21d78
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

